name: Conditional Tasks Execution

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy application'
        required: true
        default: 'false'

      user_name:
        description: 'Enter User Name'
        required: true

jobs:
  conditioChecksJob:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: echo "Building..."
      # **********************************************************************
      - name: Deploy
        if: github.event.inputs.deploy == 'true'
        run: echo "Deploying..."

      - name: PrintName
        if: ${{ inputs.user_name }}
        run: |  
            echo "User Name: ${{ inputs.user_name }}"
      # **********************************************************************
      - name: Create Variable
        run: |
          echo "FavouriteCricketer=ViratKohli" >> $GITHUB_ENV

      - name: Use Variable
        run: |
          echo "My favourite cricketer is: $FavouriteCricketer"
      # **********************************************************************
      - name: Create Output
        id: create
        run: |
          echo "FavouriteActor=SRK" >> $GITHUB_OUTPUT

      - name: Use Output
        run: |
          echo "My favourite actor is ${{ steps.create.outputs.FavouriteActor }}"
       # ********************************************************************** 
