name: DeployAzureInfrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy ARM template to Azure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run PowerShell Script
        shell: pwsh
        run: |
          ./Powershell/Get-AppConfig.ps1 `
            -FirstName "Amey" `
            -LastName "Latkar"
      
      - uses: Azure/app-configuration-import-action@v1.0.0
        with:
          name: "demo-dev-eun-aac"
          prefix: "DemoComponent:Settings:"
          label: DEV
          path: "./AppConfig/appsettings.json"
                  
      # - name: Deploy ARM template
      #   uses: azure/arm-deploy@v1
      #   with:
      #     subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #     resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
      #     resourceGroupLocation: eastus
      #     template: ./Infra/template.json
      #     parameters: ./Infra/parameters.json
      #     deploymentMode: Incremental
      #     deploymentName: deploy-storage-account
