name: DeployAzureInfrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy ARM template to Azure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run PowerShell Script
        shell: pwsh
        run: |
          ./Powershell/Get-AppConfig.ps1 `
            -FirstName "Amey" `
            -LastName "Latkar"
      
      - name: Get Azure App Configuration
        uses: flcdrg/get-azure-app-configuration-action@v6.0.16
        with:
          resourceGroup: freeresource
          appConfigurationName: amey-dev-eun-aac
          keyFilter: DemoComponent:Settings:*
          labelFilter: DEV

      - name: Print Value
        shell: pwsh
        run: |
          Write-Host $env:DemoComponent__Settings__SAName

      - name: Variable substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: './Infra/parameters.json'
        env:
          parameters.storageAccountName.value: ${{ env.DemoComponent__Settings__storageAccountName }}
          parameters.location.value: ${{ env.DemoComponent__Settings__location }}
          parameters.skuName.value: ${{ env.DemoComponent__Settings__skuName }}
          parameters.kind.value: ${{ env.DemoComponent__Settings__kind }}
          parameters.accessTier.value: ${{ env.DemoComponent__Settings__accessTier }}

      - name: Show updated file
        run: cat ./Infra/parameters.json

      - name: Deploy ARM template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          resourceGroupLocation: eastus
          template: ./Infra/template.json
          parameters: ./Infra/parameters.json
          deploymentMode: Incremental
          deploymentName: deploy-storage-account
