name: Deploy to Production

on:
  push:
    branches:
      - ameylatkar-patch-1

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    environment:
      name: prod

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Application
        run: |
          echo "Deploying to Production..."
          echo "Deployment completed successfully."
